### ISSUE TITLE
global: integrate latest changes from flask

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/flask-cli#15]
```
9594876 Added plugin support to the cli
a7d829c Update docs to the new CLI patterns
523e271 Implemented simplified CLI interface
```

also seems like this will land on v0.11 so references to 1.0 should be removed, and hopefully as soon as v0.11 is released we can deprecate this module.

**Comment by jezdez** [comment]
#16 implements that

**Comment by jezdez** [comment]
As #16 was merged, I was wondering if a 1.0 could be released to PyPI?

**Comment by jirikuncar** [comment]
https://pypi.python.org/pypi/Flask-CLI/0.4.0

**Comment by jezdez** [comment]
thanks!
