### ISSUE TITLE
flask-cli 0.4.0 update breaks Flask tutorial

### ISSUE THREAD

**Issue by ItamarLevyOr** [inveniosoftware/flask-cli#21]
The flask tutorial https://github.com/pallets/flask/tree/master/examples/flaskr gives the following error message when run:
ImportError: No module named flaskr

This problem was easily fixed by installing flask-cli 0.3.0
http://stackoverflow.com/questions/12118192/flaskr-tutorial-cant-import-flaskr-initialize-database
however this no longer works with cli 0.4.0. installing the new version of flask-cli results in the same error message.

**Comment by jirikuncar** [comment]
@ItamarLevyOr are you using Flask-CLI package with Flask<0.11?

**Comment by ItamarLevyOr** [comment]
I am using flask 0.11.1

**Comment by jirikuncar** [comment]
Then you should not use Flask-CLI but buildin CLI feature from Flask (`from flask import cli`).

**Comment by ItamarLevyOr** [comment]
Thanks

**Comment by tiborsimko** [comment]
@jirikuncar @lnielsen Shall we take this occasion to ponder whether we shouldn't pin the upper version of Flask to `<0.11` in Flask-CLI's `setup.py`? Depending on our other RFC about moving to Flask 0.11 everywhere... https://github.com/inveniosoftware/invenio/issues/3649
